version: "3.8"
services:
  app:
    container_name: app 
    build: .
    depends_on:
      - mysql
      - redis
    volumes:
      - api:/usr/src/app/
    environment:
      - PORT=8080
      - MYSQL_PORT=3306
      - REDIS_PORT=6379
      - TOKEN_EXP=900
      - TOKEN_SECRET=tap-talk
    ports:
      - 8080:8080
    networks:
      - db_network
      - redis_network

  mysql:
    container_name: mysql
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tap_talk
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network

  redis:
    container_name: redis
    image: redis:6
    ports:
      - 6379:6379
    networks: 
      - redis_network

volumes:
  api:
  mysql_data:

networks:
  db_network:
    name: db_network
  redis_network:
    name: redis_network
